name: "Sway Detection"
overview: "Suggests lowering your steering smoothness if your truck sways too much."
description: |
  ### 🛠️ First-Time Setup Recommendation

  I only recommend enabling this plugin when you're using **ETS2LA** for the **first time**, so you can fine-tune the **Steering Smoothness** setting.

  ### Where to Find It

  Go to:

  **Settings → Map → Steering**

  and adjust the **Smoothness** slider until your vehicle feels responsive but stable.

  ### Visual Example

  Below is an example of a sway detection notification:

  ![Sway Example](https://github.com/Playzzero97/Sway-Detection/blob/main/Images/example.png?raw=true)
image_url: ""
version: "1.0.0"
author: "Playzzero97"
